## YAML Template.
---
production:
  project.name: Chronic Care Clinic
  facility.name: Baobab Test Centre
  patient.registration.url: http://localhost:3005
  user.management.url: http://localhost:3004

development:
  project.name: Chronic Care Clinic
  facility.name: Baobab Test Centre
  patient.registration.url: http://localhost:3005
  user.management.url: http://localhost:3004

test: &TEST
  project.name: Chronic Care Clinic
  facility.name: Baobab Test Centre
  patient.registration.url: http://localhost:3005
  user.management.url: http://localhost:3004
