
production:
  clinical.encounters.sequential.list: ASSESSMENT,COMPLICATIONS,HIV STATUS,LAB RESULTS,OUTCOMES,TREATMENT,VITALS
  clinical.encounters.display.list: ASSESSMENT;COMPLICATIONS;HIV STATUS;LAB RESULTS;OUTCOMES;TREATMENT;VITALS
  scope: TREATMENT|,VITALS|,LAB RESULTS|,HIV STATUS|,COMPLICATIONS|,OUTCOMES|,ASSESSMENT|
  label: COMPLICATIONS|Complications,LAB RESULTS|Lab Results,ASSESSMENT|Assessment,TREATMENT|Treatment,OUTCOMES|Outcomes,VITALS|Vitals,HIV STATUS|HIV Status

development:
  clinical.encounters.sequential.list: ASSESSMENT,COMPLICATIONS,HIV STATUS,LAB RESULTS,OUTCOMES,TREATMENT,VITALS
  clinical.encounters.display.list: ASSESSMENT;COMPLICATIONS;HIV STATUS;LAB RESULTS;OUTCOMES;TREATMENT;VITALS
  scope: TREATMENT|,VITALS|,LAB RESULTS|,HIV STATUS|,COMPLICATIONS|,OUTCOMES|,ASSESSMENT|
  label: COMPLICATIONS|Complications,LAB RESULTS|Lab Results,ASSESSMENT|Assessment,TREATMENT|Treatment,OUTCOMES|Outcomes,VITALS|Vitals,HIV STATUS|HIV Status

test: &TEST
  clinical.encounters.sequential.list: ASSESSMENT,COMPLICATIONS,HIV STATUS,LAB RESULTS,OUTCOMES,TREATMENT,VITALS
  clinical.encounters.display.list: ASSESSMENT;COMPLICATIONS;HIV STATUS;LAB RESULTS;OUTCOMES;TREATMENT;VITALS
  scope: TREATMENT|,VITALS|,LAB RESULTS|,HIV STATUS|,COMPLICATIONS|,OUTCOMES|,ASSESSMENT|
  label: COMPLICATIONS|Complications,LAB RESULTS|Lab Results,ASSESSMENT|Assessment,TREATMENT|Treatment,OUTCOMES|Outcomes,VITALS|Vitals,HIV STATUS|HIV Status

