
production:
  clinical.encounters.sequential.list: COMPLICATIONS,HIV STATUS,LAB RESULTS,OUTCOMES,TREATMENT,VITALS,CLINIC VISIT,SOCIAL HISTORY,GENERAL HEALTH
  clinical.encounters.display.list: COMPLICATIONS;HIV STATUS;LAB RESULTS;OUTCOMES;TREATMENT;VITALS;CLINIC VISIT;SOCIAL HISTORY;GENERAL HEALTH
  scope: VITALS|,LAB RESULTS|,TREATMENT|,COMPLICATIONS|,OUTCOMES|,HIV STATUS|,CLINIC VISIT|,SOCIAL HISTORY|,GENERAL HEALTH
  label: COMPLICATIONS|Complications,LAB RESULTS|Lab Results,TREATMENT|Treatment,VITALS|Vitals,OUTCOMES|Outcomes,HIV STATUS|HIV Status,CLINIC VISIT|Clinic Visit,SOCIAL HISTORY|Social History,GENERAL HEALTH|General Health

development:
  clinical.encounters.sequential.list: COMPLICATIONS,HIV STATUS,LAB RESULTS,OUTCOMES,TREATMENT,VITALS,CLINIC VISIT,SOCIAL HISTORY,GENERAL HEALTH
  clinical.encounters.display.list: COMPLICATIONS;HIV STATUS;LAB RESULTS;OUTCOMES;TREATMENT;VITALS;CLINIC VISIT;SOCIAL HISTORY;GENERAL HEALTH
  scope: VITALS|,LAB RESULTS|,TREATMENT|,COMPLICATIONS|,OUTCOMES|,HIV STATUS|,CLINIC VISIT|,SOCIAL HISTORY|,GENERAL HEALTH
  label: COMPLICATIONS|Complications,LAB RESULTS|Lab Results,TREATMENT|Treatment,VITALS|Vitals,OUTCOMES|Outcomes,HIV STATUS|HIV Status,CLINIC VISIT|Clinic Visit,SOCIAL HISTORY|Social History,GENERAL HEALTH|General Health

test: &TEST
  clinical.encounters.sequential.list: COMPLICATIONS,HIV STATUS,LAB RESULTS,OUTCOMES,TREATMENT,VITALS,CLINIC VISIT,SOCIAL HISTORY,GENERAL HEALTH
  clinical.encounters.display.list: COMPLICATIONS;HIV STATUS;LAB RESULTS;OUTCOMES;TREATMENT;VITALS;CLINIC VISIT;SOCIAL HISTORY;GENERAL HEALTH
  scope: VITALS|,LAB RESULTS|,TREATMENT|,COMPLICATIONS|,OUTCOMES|,HIV STATUS|,CLINIC VISIT|,SOCIAL HISTORY|,GENERAL HEALTH
  label: COMPLICATIONS|Complications,LAB RESULTS|Lab Results,TREATMENT|Treatment,VITALS|Vitals,OUTCOMES|Outcomes,HIV STATUS|HIV Status,CLINIC VISIT|Clinic Visit,SOCIAL HISTORY|Social History,GENERAL HEALTH|General Health

