
production:
  clinical.encounters.sequential.list: COMPLICATIONS,HIV STATUS,LAB RESULTS,OUTCOMES,TREATMENT,VITALS,CLINIC VISIT
  clinical.encounters.display.list: COMPLICATIONS;HIV STATUS;LAB RESULTS;OUTCOMES;TREATMENT;VITALS;CLINIC VISIT
  scope: VITALS|,LAB RESULTS|,TREATMENT|,COMPLICATIONS|,OUTCOMES|,HIV STATUS|,CLINIC VISIT
  label: COMPLICATIONS|Complications,LAB RESULTS|Lab Results,TREATMENT|Treatment,VITALS|Vitals,OUTCOMES|Outcomes,HIV STATUS|HIV Status,CLINIC VISIT|Clinic Visit

development:
  clinical.encounters.sequential.list: COMPLICATIONS,HIV STATUS,LAB RESULTS,OUTCOMES,TREATMENT,VITALS,CLINIC VISIT
  clinical.encounters.display.list: COMPLICATIONS;HIV STATUS;LAB RESULTS;OUTCOMES;TREATMENT;VITALS;CLINIC VISIT
  scope: VITALS|,LAB RESULTS|,TREATMENT|,COMPLICATIONS|,OUTCOMES|,HIV STATUS|,CLINIC VISIT
  label: COMPLICATIONS|Complications,LAB RESULTS|Lab Results,TREATMENT|Treatment,VITALS|Vitals,OUTCOMES|Outcomes,HIV STATUS|HIV Status,CLINIC VISIT|Clinic Visit

test: &TEST
  clinical.encounters.sequential.list: COMPLICATIONS,HIV STATUS,LAB RESULTS,OUTCOMES,TREATMENT,VITALS,CLINIC VISIT
  clinical.encounters.display.list: COMPLICATIONS;HIV STATUS;LAB RESULTS;OUTCOMES;TREATMENT;VITALS;CLINIC VISIT
  scope: VITALS|,LAB RESULTS|,TREATMENT|,COMPLICATIONS|,OUTCOMES|,HIV STATUS|,CLINIC VISIT
  label: COMPLICATIONS|Complications,LAB RESULTS|Lab Results,TREATMENT|Treatment,VITALS|Vitals,OUTCOMES|Outcomes,HIV STATUS|HIV Status,CLINIC VISIT|Clinic Visit

